networks:
  oneconnect_network:
    driver: bridge
services:
  geo-map:
    build:
      context: ./geo-map # Point to the geo-map directory
      dockerfile: Dockerfile
    container_name: geo-map-api
      #ports:
      #- "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@mongodb:27017/geo-map?authSource=admin
      - FRONTEND_API=oneconnect
      - CLERK_SECRET_PUBLIC_KEY=pk_test_bm9ibGUtdGVybWl0ZS02MC5jbGVyay5hY2NvdW50cy5kZXYk
      - CLERK_SECRET_KEY=sk_test_Te3q0K3V4flEGecf2aKsBYCsHXBpo68P7zIHB4p5qr
      - CLERK_SIGNING_SECRET=whsec_a3wjlPRJ65MCknlqk+1chwzvkMAWz+O8
    depends_on:
      - mongodb
    # volumes:
    #   - ./geo-map:/usr/src/app  # Mount geo-map source code directory
    networks:
      - oneconnect_network
    restart: always # Ensure the service restarts if it fails

  oneconnect:
    build:
      context: ./oneconnect # Point to the oneconnect directory
      dockerfile: Dockerfile
      args:
        - VITE_CLERK_PUBLISHABLE_KEY=pk_test_bm9ibGUtdGVybWl0ZS02MC5jbGVyay5hY2NvdW50cy5kZXYk
        - VITE_API_BASE_URL=/api
        - VITE_API_PUBLIC_URL = geo-map-api/public/uploads
    container_name: oneconnect
    ports:
      - "80:80"
      - "443:443"
        #- "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - geo-map
        # command: npm run preview -- --host 0.0.0.0  # Use NPM to run the preview server
    networks: 
      - oneconnect_network 
    restart: always # Ensure the service restarts if it fails
      #volumes:
      #- ./oneconnect/ssl:/etc/nginx/ssl

  mongodb:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=geo-map
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    networks:
      - oneconnect_network
    restart: always # Ensure MongoDB restarts on failure
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mongodb:27017/
      # - ME_CONFIG_MONGODB_SERVER=mongodb
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=example
    ports:
      - "8081:8081" 
    depends_on:
      - mongodb
    networks:
      - oneconnect_network
    restart: always
volumes:
  mongo-data:
